[build]
  command = "npm run build && npm run export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/uqB8kxh"
  status = 200